### ISSUE TITLE
Set Location header for "Create a new authorisation" endpoint when ALREADY_AUTHORISED is returned

### ISSUE THREAD

**Issue by ubiuser** [hmrc/agent-authorisation-api#106]
Due to the missing backwards mapping of invitations to users, there is no way of telling which invitation belongs to who and vice-versa. This is a serious API desing flaw, which could be improved if the Location header was not only returned when the "Create a new authorisation" endpoint is being called and the invitaion is created successfully, but also returned when a duplicate request is made. This way the caller can map the user from the request body to the Location from the header, which contains the invitation id.

This is technically the same feature request as https://github.com/hmrc/agent-authorisation-api/issues/97, but for the ALREADY_AUTHORISED response.

**Comment by geoffreywatson** [comment]
Thanks. This is a good suggestion and we already have a ticket ready to play to add this in. We'll let you know when it's live.
