### ISSUE TITLE
Invitation page displaying "502 Bad Gateway"

### ISSUE THREAD

**Issue by tim-jackson** [hmrc/agent-authorisation-api#37]
Having generated an invitation link that should allow a client (organisation) to confirm agent authorisation, visiting the link (e.g. https://test-www.tax.service.gov.uk/invitations/CY7LR8BHG9KBW) displays a '502  Bad Gateway' nginx error.

Could be fixed? (or any timeframe of a fix?)

**Comment by BobyJordan** [comment]
I have another one.
How you succeed in Creating new authorization between the Agent and Individual?

I am receiving 204 Response Code - No content.

**Comment by arturopala** [comment]
Hi @tim-jackson, do you receive this error always or only from time to time?

**Comment by tim-jackson** [comment]
Hi @arturopala - all the time. Tried a few times with different clients etc, but have not yet visited an invitation link that hasn't displayed the error above.

**Comment by arturopala** [comment]
@tim-jackson it should be resolved now, pls try again using Planet=`hmrc` when creating client

**Comment by tim-jackson** [comment]
Thanks @arturopala - just tried again and it's now working fine. Many Thanks

**Comment by tim-jackson** [comment]
@arturopala - The same problem as yesterday is recurring again today.

**Comment by arturopala** [comment]
@tim-jackson this is probably due to service instances recycling, should work now again

**Comment by tim-jackson** [comment]
Ok, thanks
