### ISSUE TITLE
Response status - 204 - No content

### ISSUE THREAD

**Issue by BobyJordan** [hmrc/agent-authorisation-api#38]
Hello all,

I am struggling with creating an authorization link between test Agent and test Individual as I am getting Status code 204 as a response.

What I am doing is:

**Create Agent data via this API:**
[https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/api-platform-test-user/1.0](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/api-platform-test-user/1.0 )

**Authorize the Agent with all the needed scopes: via this API:** 
(in my case: _read:check-relationship_, _read:vat_, _write:sent-invitations_, _write:vat_, _read:sent-invitations_)
[https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints
)

**Create Client (Organisation or Individual) data via this stub:**
(following step by step the tutorial, using the Application ### clientId from the dev hub as a **Planet**, creating the needed test user as Individual)
[https://test-www.tax.service.gov.uk/agents-external-stubs/help/agent-authorisation-api](https://test-www.tax.service.gov.uk/agents-external-stubs/help/agent-authorisation-api)

**Trying to create new authorisation between Agent and Individual:**
[https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/agent-authorisation-api/1.0#_create-a-new-authorisation_post_accordion](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/agent-authorisation-api/1.0#_create-a-new-authorisation_post_accordion)

As taking the **_clientId_** and _**knownFact**_ from the External Stub.

### **My Authorisation token:** --- the ARN and Bearer token are taken from the Agent, created by the API, not external stub
![authorisation](https://user-images.githubusercontent.com/28267765/51852049-e5f43c80-232d-11e9-8130-39ed094153e7.JPG)

### **My header** --- the X-Session-ID is the same in all users in external stub
![header](https://user-images.githubusercontent.com/28267765/51852065-f1dffe80-232d-11e9-9f1b-f82f5958bef8.JPG)

### **My request body** --- the clientId and knownFact is taken from the external stub Individual user for HMRC-MTD-VAT service key

![no content](https://user-images.githubusercontent.com/28267765/51851915-97df3900-232d-11e9-81d0-a63dda3b0f34.JPG)

I had difficulties with this for three weeks. 
Any help or guides would be useful.

**Comment by arturopala** [comment]
Hi @BobyJordan, the response you get means success, you should be able to use URL from the LOCATION header to get invitation status.

**Comment by arturopala** [comment]
@BobyJordan you should use `hmrc` as a planet name when creating users in stubs, this has changed some weeks ago.

**Comment by BobyJordan** [comment]
Yes, I have done that.

![external stubs](https://user-images.githubusercontent.com/28267765/51853522-302aed00-2331-11e9-8e87-92d988e9169a.JPG)

**Comment by BobyJordan** [comment]
Or.. you mean like this:

![hmrc as planet](https://user-images.githubusercontent.com/28267765/51853643-708a6b00-2331-11e9-8744-267c1d3d9e52.JPG)

**Comment by arturopala** [comment]
@BobyJordan I mean Planet=`hmrc`

**Comment by arturopala** [comment]
@BobyJordan good, can we help you more or the issue is resolved?

**Comment by BobyJordan** [comment]
@arturopala The issue is resolved.
