### ISSUE TITLE
NO_PERMISSION_ON_AGENCY

### ISSUE THREAD

**Issue by ramanbatra152** [hmrc/agent-authorisation-api#52]
While checking relationship , one of the agent getting the error 'NO_PERMISSION_ON_AGENCY' stating "The user that is signed in cannot access this authorization request. Their details do not match the agent business that created the authorization request". Can I get more clarification on this?

**Comment by JTY009** [comment]
Hi @ramanbatra152,

This occurs if the arn part of the url does not match to the arn in the credential of the user.

For example

request url: /agents/TARN0000001/relationships

but the logged in agent has TARN0000002. 

They will not match noted here: https://github.com/hmrc/agent-authorisation-api/blob/master/app/uk/gov/hmrc/agentauthorisation/controllers/api/agent/AgentController.scala#L281

I would advise cross checking the arn used in the request url and the logged in agent's arn.

**Comment by ramanbatra152** [comment]
we are getting this issue in live APIs , can you confirm is there any validation for ARN like no. of characters etc.

**Comment by JTY009** [comment]
Hi @ramanbatra152,

is this issue ongoing? because I noticed yesterday you raised another issue asking a similar question like above, which also got answered.

**Comment by ramanbatra152** [comment]
The issue is resolved from my end.. Thanks for the reply.. You can close
this issue..

**Comment by JTY009** [comment]
No problem
