### ISSUE TITLE
Agent-Authorisation-API for Organisations

### ISSUE THREAD

**Issue by Byordanova8** [hmrc/agent-authorisation-api#59]
Hi guys,
I am facing an issue with the Agent-Authorisation API for an organization in **Production** environment. Since this current service is only available in Test/Sandbox version.

Am I misled about those environments?
If I am not, where we could expect it in a Production environment?

Thank you in advance!

**Comment by JTY009** [comment]
Hi @Byordanova8, 

The API is in production and in sandbox as well.

Can you add more detail to the issue you are facing?

- What API are you attempting to call?

- Can you provide the request you made?

- What is the Payload if it is the create invitation / check relationship?

You mentioned "Organization", you need to have a goverment gateway account that was created as an Agent.

Kind Regards

**Comment by Byordanova8** [comment]
- Agent Authorisation API
- Relationship: Agent - Organisation

The MTD VAT Agent authorization API is in both - production and sandbox, but the agent could take action only for the users "Individual", but not for "Organisation".

If there is already that kind of service, how I could have access to it?

Currently, I have:
Real (Production) Agent account
Real (Production) Organisation account - clients, which have given the rights to the Agent to Submit VAT Return from their name.

Thank you in advance!

**Comment by johnrevill** [comment]
We're not quite sure which URL for this API you are having issues with.
Do you mean the `POST /agents/{arn}/invitations` URL ("Create a new authorisation")?

Or if you mean that the client Organisation is having difficulties responding to the authorisation request, could you let us know the specific error/problem that is seen by the client?

Or, do you mean that the agent is having difficulties acting on behalf of the client Organisation? If this is the case, has the client Organisation accepted the authorisation request? 
It's possible to check whether the authorisation request has been accepted or not from the "Track your recent authorisation requests" link in your Agent Services account home page. You can access that from https://www.tax.service.gov.uk/agent-services-account whilst logged in with your agent account.

**Comment by Byordanova8** [comment]
In order to summarise my question.

- How to get the Agent Authorisation API for production?
https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/agent-authorisation-api/1.0

- Is it possible to send an invitation to **Organisation** user?

**Comment by johnrevill** [comment]
> - How to get the Agent Authorisation API for production?

Firstly, could we check if step 4 in https://developer.service.hmrc.gov.uk/api-documentation/docs/using-the-hub has been completed?

A new application will be needed for the production environment, separate to any existing application in the sandbox environment. 
You can add a new application from https://developer.service.hmrc.gov.uk/developer/applications/add where you can select the production environment.

Once you've created an application, you can view it in https://developer.service.hmrc.gov.uk/developer/applications and if you click on the link from there, you can see some crucial details about the application. 
In particular, I'd highlight the following:
1. the subscription toggle "APIs"->"Agent Authorisation"->"1.0 (Beta)" under the "Manage API subscriptions" section, which should be set to "On".
2. the "Client ID" and "Client secrets" under the "Manage credentials" section will allow you to go through the OAuth journey (more details on OAuth are at https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints)

Another thing to note is that the production base URL (https://api.service.hmrc.gov.uk) is slightly different to the sandbox base URL (https://test-api.service.hmrc.gov.uk).


> - Is it possible to send an invitation to Organisation user?

If you are asking: can the invitation link be emailed to the client by HMRC? - the answer is no. 
The API will only provide the invitaion link to the agent and the agent must then provide this link to the client themselves. 


But if you're asking: are Organisation client users supported by the API? - the answer is yes. 
To create an authorisation request for an Organisation, take a look to https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/agent-authorisation-api/1.0#_create-a-new-authorisation_post_accordion 
Under the "Request" heading on that page there are two example requests; the second request example is for an organisation. 
In particular, the `clientType` must have a value of "business", e.g.:
```
{
  "service": ["MTD-VAT"],
  "clientType":"business",
  "clientIdType": "vrn",
  "clientId": "101747696",
  "knownFact": "2007-05-18"
}
```

**Comment by Byordanova8** [comment]
Thank you for your time, @johnrevill!


I have requested a subscription to Agent Authorisation API.

**Comment by JTY009** [comment]
Hi @Byordanova8,

Is this still an issue or can we close it?

**Comment by Byordanova8** [comment]
You can close it. @JTY009
