### ISSUE TITLE
Test env: unable to work with Client self-assessment using authorized Agent

### ISSUE THREAD

**Issue by anlar** [hmrc/agent-authorisation-api#83]
I'm using HMRC test environment to work with MTD API's for self-assessment. My understanding from MTD Guide is that after Client authorized Agent application should be able to use self-assessment API's with Agents credentials.

So I have Agent: `{ "userId": "447156127007", "agentServicesAccountNumber": "WARN0792948" }`, Client: `{
"userId": "651359909411","nino": "WW202851A" }` - both created via Test User API. Agent has a request to Client which is authorized:

```
[
    {
        "_links": {
            "self": {
                "href": "/agents/WARN0792948/invitations/A36H711LRXA85"
            }
        },
        "created": "2021-07-27T09:03:56.241Z",
        "arn": "WARN0792948",
        "service": [
            "MTD-IT"
        ],
        "status": "Accepted",
        "updated": "2021-07-27T09:11:25.974Z"
    }
]
```

I have also checked Agent Stubs and there exists a Delegated enrollment entry for my Agent/Client relation.

When I'm using Clients credentials I'm able to use all MTD-related API's - obligations, business details, self-assessment, individual calculations. But with Agents credentials I'm getting following error responses for the same endpoints:

```
{
    "code": "CLIENT_OR_AGENT_NOT_AUTHORISED",
    "message": "The client and/or agent is not authorised"
}
```

or

```
{
    "code": "AGENT_NOT_AUTHORIZED",
    "message": "The agent is not authorized"
}
```

Could you please advise if there are some additional steps to authorize Agent that I'm missing.

**Comment by geoffreywatson** [comment]
Unfortunately this is expected. The reason being that the stubs that back agent services are different to those that back other services (like SA), so a bearer token issued by one stub will not necessarily be valid when you access other services. This explains the unauthorised response you are seeing when your agent tries to access an API for their client.

**Comment by anlar** [comment]
@geoffreywatson Thank you for explanation.
And just to confirm, in live environment it is expected that application should be able to use MTD API's with both Clients and authorized Agents credentials?

**Comment by geoffreywatson** [comment]
Correct.

**Comment by anlar** [comment]
Great, thank you.
