### ISSUE TITLE
Invitations endpoint does not accept businesses

### ISSUE THREAD

**Issue by coderms** [hmrc/agent-authorisation-api#87]
Hi,
our application is connecting to HMRC test endpoint to create invite.

It’s creating organization with request to:
https://test-api.service.hmrc.gov.uk/create-test-user/organisations

Response:
{"userId"=>"928105991016", "password"=>"ogbbwma7nl6x", "userFullName"=>"Frankie Stafford", "emailAddress"=>"frankie.stafford@example.com", "organisationDetails"=>{"name"=>"Company CIRAD9", "address"=>{"line1"=>"10 Jamaica Road", "line2"=>"Edinburgh", "postcode"=>"TS17 1PA"}}, "individualDetails"=>{"firstName"=>"Frankie", "lastName"=>"Stafford", "dateOfBirth"=>"1967-05-23", "address"=>{"line1"=>"17 Queensway", "line2"=>"Bath", "postcode"=>"TS19 1PA"}}, "saUtr"=>"6590365321", "nino"=>"HY186626D", "mtdItId"=>"XNIT00661772817", "empRef"=>"229/TI4WL8OMYD", "ctUtr"=>"3230825992", "vrn"=>"689136196", "vatRegistrationDate"=>"2009-11-29", "groupIdentifier"=>"939581236939", "crn"=>"4208510522", "taxpayerType"=>"Individual"}

Then it’s creating agent with request to:
https://test-api.service.hmrc.gov.uk/create-test-user/agents

Response:
{"userId"=>"920835266921", "password"=>"ywj7pfqg9fgr", "userFullName"=>"Dale Croft", "emailAddress"=>"dale.croft@example.com", "agentServicesAccountNumber"=>"ZARN0614474", "agentCode"=>"776522448508", "groupIdentifier"=>"2889716214"}

Then it’s POST requesting /invitations endpoint with:
https://test-api.service.hmrc.gov.uk/agents/ZARN0614474/invitations
With body:
{
  "service": [
    "MTD-VAT"
  ],
  "clientType": "business",
  "clientIdType": "vrn",
  "clientId": "689136196",
  "knownFact": "2009-11-29"
}
Payload created from previous requests (pasted above).

We are not receiving success response but error:
{
  "code": "CLIENT_REGISTRATION_NOT_FOUND",
  "message": "The details provided for this client do not match HMRC's records."
}

Test for individual (not business) is working.
Is invitations endpoint accepting businesses?

**Comment by geoffreywatson** [comment]
Hi, thanks for raising this issue. It appears that the services profile contains identifiers that result in a conflict with our agent stubs. We are working on a fix for this but in the meantime could you try to create another organisation test user but select only 'mtd-vat'?

**Comment by coderms** [comment]
It works with 'mtd-vat' only. I'm going to update my tests. Thanks!

**Comment by geoffreywatson** [comment]
no problem! closing the issue.
