### ISSUE TITLE
Set Location header for "Create a new authorisation" endpoint when DUPLICATE_AUTHORISATION_REQUEST is returned

### ISSUE THREAD

**Issue by ubiuser** [hmrc/agent-authorisation-api#97]
Due to the missing backwards mapping of invitations to users, there is no way of telling which invitation belongs to who and vice-versa. This is a serious API desing flaw, which could be improved if the Location header was not only returned when the "Create a new authorisation" endpoint is being called and the invitaion is created successfully, but also returned when a duplicate request is made. This way the caller can map the user from the request body to the Location from the header, which contains the invitation id.

**Comment by geoffreywatson** [comment]
Hi, we can provide the Location header in this response. I'll update this issue when completed.

**Comment by ubiuser** [comment]
Any update on this?
